apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiuwjd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiuwjd
  template:
    metadata:
      labels:
        app: aiuwjd
    spec:
      containers:
      - image: okteto.dev/aiuwjd:latest
        name: aiuwjd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6beb3dac-3775-4221-aa35-541a19d1d7ae"
        - name: Vless_Path
          value: "/6beb3dac-3775-4221-aa35-541a19d1d7ae-vless"
        - name: Vmess_UUID
          value: "6beb3dac-3775-4221-aa35-541a19d1d7ae"
        - name: Vmess_Path
          value: "/6beb3dac-3775-4221-aa35-541a19d1d7ae-vmess"
        - name: Share_Path
          value: "/6beb3dac-3775-4221-aa35-541a19d1d7ae-link"
